### ISSUE TITLE
Write output into a geojson file

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/assetInventory#1]
write output csv as a geojson file. see https://gis.stackexchange.com/questions/130963/write-geojson-into-a-geojson-file-with-python

**Comment by kbailey-noaa** [comment]
@MathewBiddle Not sure how to import this into Google Earth, so was wondering if you'd be able to convert to a .kml or .kmz file?

**Comment by MathewBiddle** [comment]
Let me see what other formats geopandas can write out. I'll update when I find out more.

**Comment by MathewBiddle** [comment]
@kbailey-noaa See if [this kml](https://github.com/MathewBiddle/assetInventory/blob/master/2020/processed_inventory.kml) works. I'll keep looking into kmz as well.

**Comment by kbailey-noaa** [comment]
Got it, thanks!!

**Comment by MathewBiddle** [comment]
@kbailey-noaa, I found a bug in my code where I wasn't capturing some of the ph and salinity data types. It should be fixed now and the respective files have been updated.

**Comment by MathewBiddle** [comment]
seems to be resolved
