### ISSUE TITLE
Processed inventory fields

### ISSUE THREAD

**Issue by kbailey-noaa** [MathewBiddle/assetInventory#19]
I'm trying to glean info from the processed inventory .csv but that file contains a subset of the full list of fields provided. e.g. WMO ID, operator sector, etc are missing.  Is there a copy of the complete processed inventory I could download?

**Comment by MathewBiddle** [comment]
The raw inventory is here https://github.com/MathewBiddle/assetInventory/blob/master/2020/combined_raw_inventory.csv

That is a simple concatenation of all the excel spreadsheets and dumped into a csv file. 

Let me know if you need something else or if I could organize this better.
